<?php

namespace Circles;

use Circles\Circle;
use JetBrains\PhpStorm\Pure;

class Cylinder extends Circle
{
    public float|int $height;

    #[Pure] public function __construct(float $radius, string $color, float|int $height)
    {
        parent::__construct($radius, $color);
        $this->height = $height;
    }

    public function calculateVolume(): float|int
    {
        return $this->area * $this->height;
    }

    #[Pure] public function __toString(): string
    {
        return "Cylinder { Radius :" . $this->radius . " ,Height :" . $this->height . " ,Color :" . $this->color . " ,Volume : " . $this->calculateVolume() . "}"; // TODO: Change the autogenerated stub
    }
}